### ISSUE TITLE
hexo g  报错

### ISSUE THREAD

**Issue by horysk** [howardliu-cn/hexo-theme-clean-dark#1]
ERROR { ReferenceError: /b-clean-dark/themes/hexo-theme-clean-dark/layout/post.ejs:17
    15|         </div>
    16|         <div class="post-content article-entry">
 >> 17|             
    18|             <%- page.content %>
    19|         </div>
    20|         <% if(page.tags){ %>

/b-clean-dark/themes/hexo-theme-clean-dark/layout/_partial/toc.ejs:1
 >> 1| <% if (post.toc != false) { %>
    2|     <div id="toc">
    3|       <%- toc(post.content, {list_number: false}) %>
    4|     </div>

post is not defined
    at eval (/b-clean-dark/themes/hexo-theme-clean-dark/layout/_partial/toc.ejs:10:8)
    at toc (/b-clean-dark/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync.locals [as _compiledSync] (/b-clean-dark/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/b-clean-dark/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/b-clean-dark/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/b-clean-dark/themes/hexo-theme-clean-dark/layout/post.ejs:25:17)
    at post (/b-clean-dark/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled.locals [as _compiled] (/b-clean-dark/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/b-clean-dark/node_modules/hexo/lib/theme/view.js:39:17)
    at /b-clean-dark/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/b-clean-dark/node_modules/bluebird/js/release/util.js:16:23)
    at /b-clean-dark/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/b-clean-dark/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:471:10)
    at resume_ (_stream_readable.js:950:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  path: '/b-clean-dark/themes/hexo-theme-clean-dark/layout/post.ejs' }
ERROR { ReferenceError: /b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs:6
    4|
    5|         <div class="post">
 >> 6|             <%
    7|             if(page.archive) {
    8|             if(page.year) {
    9|             if (page.month) {

_ is not defined
    at eval (/b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs:105:30)
    at archive (/b-clean-dark/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled.locals [as _compiled] (/b-clean-dark/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/b-clean-dark/node_modules/hexo/lib/theme/view.js:39:17)
    at /b-clean-dark/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/b-clean-dark/node_modules/bluebird/js/release/util.js:16:23)
    at /b-clean-dark/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/b-clean-dark/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:471:10)
    at resume_ (_stream_readable.js:950:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  path:
   '/b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs' }
ERROR { ReferenceError: /b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs:6
    4|
    5|         <div class="post">
 >> 6|             <%
    7|             if(page.archive) {
    8|             if(page.year) {
    9|             if (page.month) {

_ is not defined
    at eval (/b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs:50:38)
    at archive (/b-clean-dark/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled.locals [as _compiled] (/b-clean-dark/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/b-clean-dark/node_modules/hexo/lib/theme/view.js:39:17)
    at /b-clean-dark/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/b-clean-dark/node_modules/bluebird/js/release/util.js:16:23)
    at /b-clean-dark/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/b-clean-dark/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:471:10)
    at resume_ (_stream_readable.js:950:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  path:
   '/b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs' }

**Comment by howardliu-cn** [comment]
> ERROR { ReferenceError: /b-clean-dark/themes/hexo-theme-clean-dark/layout/post.ejs:17
> 15|
> 16|
> 
> > > 17|             
> > > 18|             <%- page.content %>
> > > 19|
> 
> 
> 20| <% if(page.tags){ %>
> /b-clean-dark/themes/hexo-theme-clean-dark/layout/_partial/toc.ejs:1
> 
> > > 1| <% if (post.toc != false) { %>
> > > 2|     
> > > 3|       <%- toc(post.content, {list_number: false}) %>
> > > 4|
> 
> post is not defined
> at eval (/b-clean-dark/themes/hexo-theme-clean-dark/layout/_partial/toc.ejs:10:8)
> at toc (/b-clean-dark/node_modules/ejs/lib/ejs.js:682:17)
> at _View._compiledSync.locals [as _compiledSync] (/b-clean-dark/node_modules/hexo/lib/theme/view.js:132:24)
> at _View.renderSync (/b-clean-dark/node_modules/hexo/lib/theme/view.js:59:25)
> at Object.partial (/b-clean-dark/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
> at eval (/b-clean-dark/themes/hexo-theme-clean-dark/layout/post.ejs:25:17)
> at post (/b-clean-dark/node_modules/ejs/lib/ejs.js:682:17)
> at _View._compiled.locals [as _compiled] (/b-clean-dark/node_modules/hexo/lib/theme/view.js:136:50)
> at _View.render (/b-clean-dark/node_modules/hexo/lib/theme/view.js:39:17)
> at /b-clean-dark/node_modules/hexo/lib/hexo/index.js:64:21
> at tryCatcher (/b-clean-dark/node_modules/bluebird/js/release/util.js:16:23)
> at /b-clean-dark/node_modules/bluebird/js/release/method.js:15:34
> at RouteStream._read (/b-clean-dark/node_modules/hexo/lib/hexo/router.js:47:5)
> at RouteStream.Readable.read (_stream_readable.js:471:10) at resume_ (_stream_readable.js:950:12)
> at process._tickCallback (internal/process/next_tick.js:63:19)
> path: '/b-clean-dark/themes/hexo-theme-clean-dark/layout/post.ejs' }
> ERROR { ReferenceError: /b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs:6
> 4|
> 5|
> 
> > > 6|             <%
> > > 7|             if(page.archive) {
> > > 8|             if(page.year) {
> > > 9|             if (page.month) {
> 
> _ is not defined
> at eval (/b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs:105:30)
> at archive (/b-clean-dark/node_modules/ejs/lib/ejs.js:682:17)
> at _View._compiled.locals [as _compiled] (/b-clean-dark/node_modules/hexo/lib/theme/view.js:136:50)
> at _View.render (/b-clean-dark/node_modules/hexo/lib/theme/view.js:39:17)
> at /b-clean-dark/node_modules/hexo/lib/hexo/index.js:64:21
> at tryCatcher (/b-clean-dark/node_modules/bluebird/js/release/util.js:16:23)
> at /b-clean-dark/node_modules/bluebird/js/release/method.js:15:34
> at RouteStream._read (/b-clean-dark/node_modules/hexo/lib/hexo/router.js:47:5)
> at RouteStream.Readable.read (_stream_readable.js:471:10) at resume_ (_stream_readable.js:950:12)
> at process._tickCallback (internal/process/next_tick.js:63:19)
> path:
> '/b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs' }
> ERROR { ReferenceError: /b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs:6
> 4|
> 5|
> 
> > > 6|             <%
> > > 7|             if(page.archive) {
> > > 8|             if(page.year) {
> > > 9|             if (page.month) {
> 
> _ is not defined
> at eval (/b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs:50:38)
> at archive (/b-clean-dark/node_modules/ejs/lib/ejs.js:682:17)
> at _View._compiled.locals [as _compiled] (/b-clean-dark/node_modules/hexo/lib/theme/view.js:136:50)
> at _View.render (/b-clean-dark/node_modules/hexo/lib/theme/view.js:39:17)
> at /b-clean-dark/node_modules/hexo/lib/hexo/index.js:64:21
> at tryCatcher (/b-clean-dark/node_modules/bluebird/js/release/util.js:16:23)
> at /b-clean-dark/node_modules/bluebird/js/release/method.js:15:34
> at RouteStream._read (/b-clean-dark/node_modules/hexo/lib/hexo/router.js:47:5)
> at RouteStream.Readable.read (_stream_readable.js:471:10) at resume_ (_stream_readable.js:950:12)
> at process._tickCallback (internal/process/next_tick.js:63:19)
> path:
> '/b-clean-dark/themes/hexo-theme-clean-dark/layout/archive.ejs' }

我试一下哈，因为我自己一直在用，之前没有发现有什么报错

**Comment by WaxRain** [comment]
同上错误，不知是否解决？

**Comment by WaxRain** [comment]
同上错误，不知是否已解决？

**Comment by howardliu-cn** [comment]
> 同上错误，不知是否已解决？

可以下载最新的代码，使用hexo 6.0.0可以正常使用

**Comment by howardliu-cn** [comment]
@horysk @WaxRain 异常已修复，这个issue就先关闭了，如果有问题可以继续回复或者开新的issue。
